# **<center> Введение в Python, New Economic School, MAE 2022 </center>**
## **<center> Занятие 3 </center>**

План:

* NumPy
* Pandas
* Обработка дат и времени

Материалы базируются на семинаре Евгения Соколова по Машинному Обучению 1 

## **NumPy**

<center> <img src="https://user-images.githubusercontent.com/1217238/65354639-dd928f80-dba4-11e9-833b-bc3e8c6a737d.png" width=50%> </center>

**NumPy** - библиотека для работы с многомерными массивами, векторами и матрицами. Данная бибилиотека реализует удобный функционал такой работы, а также для проведения различных математических операций над ними.

[Документация](https://numpy.org/doc/)

Основной тип данных - многомерный массив элементов - `numpy.ndarray`. Каждый такой массив имеет несколько измерений (вектор с одним измерением, матрица с двумя и т.д.)

In [ ]:
import numpy as np

import warnings
warnings.simplefilter("ignore")

Количество измерений

In [ ]:
vec = np.array([1, 2, 3])
vec.ndim 

1

In [ ]:
matrix = np.array([[5, 7, 4], [4, 5, 9]])
matrix.ndim

2

Длина массива по каждой из осей

In [ ]:
vec.shape

(3,)

In [ ]:
matrix.shape

(2, 3)

Тип элементов в массиве

In [ ]:
matrix.dtype.name

'int64'

Размер массива в байтах

In [ ]:
matrix.itemsize

8

Создание массива

In [ ]:
A = np.array([1, 2, 3])
A, A.dtype

(array([1, 2, 3]), dtype('int64'))

In [ ]:
A = np.array([1, 2, 3], dtype = float)
A, A.dtype

(array([1., 2., 3.]), dtype('float64'))

Создание массивов специальных видов

* массив из нулей
* массив из единиц
* единичная матрица

In [ ]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Также можно создать последовательности при помощи функции `arange` (параметры на входе - левая граница, правая граница и **шаг**) и `linspace` (параметры на входе - левая и правая границы и **количество** элементов)

In [ ]:
np.arange(3, 20, 3) # аналогично стандартной функции range python, правая граница не включается

array([ 3,  6,  9, 12, 15, 18])

In [ ]:
np.arange(2.5, 8.7, 0.9) # также может работать и с вещественными числами

array([2.5, 3.4, 4.3, 5.2, 6.1, 7. , 7.9])

In [ ]:
np.linspace(2, 18, 14) # правая граница включается (по умолчанию)

array([ 2.        ,  3.23076923,  4.46153846,  5.69230769,  6.92307692,
        8.15384615,  9.38461538, 10.61538462, 11.84615385, 13.07692308,
       14.30769231, 15.53846154, 16.76923077, 18.        ])

Можно менять размер существующих массивов, пользуясь функцией `reshape`.

In [ ]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Вместо значения длины массива по одному из измерений можно указать -1 — в этом случае значение будет рассчитано автоматически:

In [ ]:
np.arange(10).reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Можно массив и транспонировать

In [ ]:
A = np.arange(8).reshape(2, -1)
A

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
A.T

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [ ]:
A.shape, A.T.shape

((2, 4), (4, 2))

Можно повторить массив

In [ ]:
a = np.arange(3)
np.tile(a, (2, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [ ]:
np.tile(a, (4, 1))

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

Базовые арифметические операции между массивами по умолчанию производятся поэлеметно

In [ ]:
A = np.random.randint(-5, 5, (3, 3))
B = np.random.randint(-7, 7, (3, 3))

In [ ]:
A

array([[-3,  4, -4],
       [ 2, -3, -1],
       [ 2,  1,  3]])

In [ ]:
B

array([[ 2,  1,  6],
       [-1,  4,  0],
       [ 0, -4, -4]])

In [ ]:
A + B

array([[-1,  5,  2],
       [ 1,  1, -1],
       [ 2, -3, -1]])

In [ ]:
A * B

array([[ -6,   4, -24],
       [ -2, -12,   0],
       [  0,  -4, -12]])

In [ ]:
A / B

array([[-1.5       ,  4.        , -0.66666667],
       [-2.        , -0.75      ,        -inf],
       [        inf, -0.25      , -0.75      ]])

In [ ]:
A // B

array([[-2,  4, -1],
       [-2, -1,  0],
       [ 0, -1, -1]])

In [ ]:
3 * A

array([[ -9,  12, -12],
       [  6,  -9,  -3],
       [  6,   3,   9]])

In [ ]:
3 * A - B

array([[-11,  11, -18],
       [  7, -13,  -3],
       [  6,   7,  13]])

In [ ]:
3 * A - B + 1

array([[-10,  12, -17],
       [  8, -12,  -2],
       [  7,   8,  14]])

Матричное умножение происходит через метод `dot`, взятую от одного массива. В функцию аргументом передается другой массив. Обращайте внимание на размерности.

Также можно использовать функцию `matmul` в `numpy`. Аргументами передаются массивы.

In [ ]:
A.dot(B)

array([[-10,  29,  -2],
       [  7,  -6,  16],
       [  3,  -6,   0]])

In [ ]:
np.matmul(A, B)

array([[-10,  29,  -2],
       [  7,  -6,  16],
       [  3,  -6,   0]])

[Про broadcasting](http://scipy-lectures.org/intro/numpy/operations.html#broadcasting)

Некоторые операции над массивами (например, вычисления минимума, максимума, суммы элементов) выполняются над всеми элементами вне зависимости от формы массива, однако при указании оси выполняются вдоль нее (например, для нахождения максимума каждой строки или каждого столбца):

In [ ]:
A

array([[-3,  4, -4],
       [ 2, -3, -1],
       [ 2,  1,  3]])

In [ ]:
A.min()

-4

In [ ]:
A.min(axis = 0) # минимум по элементам столбцов

array([-3, -3, -4])

In [ ]:
A.min(axis = 1) # минимум по элементам строк

array([-4, -3,  1])

In [ ]:
A.sum(axis = 0)

array([ 1,  2, -2])

In [ ]:
A.sum(axis = 1)

array([-3, -2,  6])

In [ ]:
A

array([[-3,  4, -4],
       [ 2, -3, -1],
       [ 2,  1,  3]])

In [ ]:
A.argmax(axis = 0 )

array([1, 0, 2])

In [ ]:
A.argmax(axis = 1)

array([0, 2, 0])

Можно оборачивать матрицы, можно брать определитель

In [ ]:
A

array([[-3,  4, -4],
       [ 2, -3, -1],
       [ 2,  1,  3]])

In [ ]:
np.linalg.inv(A)

array([[ 0.2  ,  0.4  ,  0.4  ],
       [ 0.2  ,  0.025,  0.275],
       [-0.2  , -0.275, -0.025]])

In [ ]:
np.linalg.det(A)

-40.000000000000014

In [ ]:
np.linalg.eigvals(A)

array([-5.66120568+0.j        ,  1.33060284+2.30111468j,
        1.33060284-2.30111468j])

In [ ]:
np.linalg.matrix_power(A, 3)

array([[ -91,  116,  -20],
       [  58, -112,   16],
       [  10,  -16,  -16]])

In [ ]:
np.linalg.matrix_rank(A)

3

\begin{equation} \beta X = y \end{equation}

In [ ]:
np.linalg.lstsq(A, np.array([1, 2, 3]))

(array([ 2.2  ,  1.075, -0.825]),
 array([], dtype=float64),
 3,
 array([7.1442832 , 4.        , 1.39972055]))

In [ ]:
np.linalg.lstsq(A, np.array([1, 2, 3]))[0]

array([ 2.2  ,  1.075, -0.825])

In [ ]:
np.median(A)

1.0

In [ ]:
np.median(A, axis = 0)

array([ 2.,  1., -1.])

In [ ]:
np.quantile(A, 0.95)

3.5999999999999996

In [ ]:
np.quantile(A, 0.95, axis = 1)

array([3.3, 1.7, 2.9])

In [ ]:
np.floor(2.5)

2.0

In [ ]:
np.ceil(2.4)

3.0

In [ ]:
np.round(2.55, 1)

2.6

Для доступа к элементам может использоваться [много различных способов](http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html), рассмотрим основные.

Для индексации могут использоваться конкретные значения индексов и срезы (slice), как и в стандартных типах Python. Для многомерных массивов индексы для различных осей разделяются запятой. Если для многомерного массива указаны индексы не для всех измерений, недостающие заполняются полным срезом (:).

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[2:5]

array([2, 3, 4])

In [ ]:
a[3:8:2]

array([3, 5, 7])

In [ ]:
A = np.arange(81).reshape(9, -1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [ ]:
A[2:4]

array([[18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [ ]:
A[:, 2:4]

array([[ 2,  3],
       [11, 12],
       [20, 21],
       [29, 30],
       [38, 39],
       [47, 48],
       [56, 57],
       [65, 66],
       [74, 75]])

In [ ]:
A[2:4, 2:4]

array([[20, 21],
       [29, 30]])

In [ ]:
A[-2]

array([63, 64, 65, 66, 67, 68, 69, 70, 71])

Также можно в срезы добавлять список индексов по измерениям

In [ ]:
A = np.arange(81).reshape(9, -1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [ ]:
A[[2, 4, 5], [0, 1, 3]]

array([18, 37, 48])

Можно применять логическую индексацию

In [ ]:
A = np.arange(11)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
A % 5 != 3

array([ True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True])

In [ ]:
A[A % 5 != 3]

array([ 0,  1,  2,  4,  5,  6,  7,  9, 10])

In [ ]:
A[np.logical_and(A != 7, A % 5 != 3)] # также можно использовать логические операции

array([ 0,  1,  2,  4,  5,  6,  9, 10])

In [ ]:
A[(A != 7) & (A % 5 != 3)] # также можно использовать логические операции

array([ 0,  1,  2,  4,  5,  6,  9, 10])

In [ ]:
A = np.arange(12).reshape(3, -1)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
A.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
A[(A != 7) & (A % 5 != 3)] 

array([ 0,  1,  2,  4,  5,  6,  9, 10, 11])

In [ ]:
np.where(A % 3 == 0)

(array([0, 0, 1, 2]), array([0, 3, 2, 1]))

In [ ]:
A[np.where(A % 3 == 0)]

array([0, 3, 6, 9])

In [ ]:
np.where(A % 3 == 0, A, 'Condition False')

array([['0', 'Condition False', 'Condition False', '3'],
       ['Condition False', 'Condition False', '6', 'Condition False'],
       ['Condition False', '9', 'Condition False', 'Condition False']],
      dtype='<U21')

Также массивы можно конкатенировать

In [ ]:
A = np.random.randint(-5, 5, size = (2, 2))
B = np.random.randint(-7, 7, size = (2, 2))
C = np.random.randint(-7, 7, size = (2, 1))

In [ ]:
A

array([[-4,  0],
       [ 1, -2]])

In [ ]:
B

array([[-4, -5],
       [ 5, -2]])

In [ ]:
C

array([[3],
       [5]])

In [ ]:
np.hstack((A, B))

array([[-4,  0, -4, -5],
       [ 1, -2,  5, -2]])

In [ ]:
np.hstack((A, B, A))

array([[-4,  0, -4, -5, -4,  0],
       [ 1, -2,  5, -2,  1, -2]])

In [ ]:
np.vstack((A, B))

array([[-4,  0],
       [ 1, -2],
       [-4, -5],
       [ 5, -2]])

In [ ]:
A, A.shape

(array([[-4,  0],
        [ 1, -2]]), (2, 2))

In [ ]:
C, C.shape

(array([[3],
        [5]]), (2, 1))

In [ ]:
np.hstack((A, C))

array([[-4,  0,  3],
       [ 1, -2,  5]])

In [ ]:
np.vstack((A, C))

ValueError: ignored

Зачем необходимо использовать NumPy, если существуют стандартные списки/кортежи и циклы?

Причина заключается в скорости работы, а также в удобном обширном реализованном функционале. Попробуем посчитать скалярное произведение 2 больших векторов:

In [ ]:
SIZE = 10000000

A_quick_arr = np.random.normal(size = (SIZE,))
B_quick_arr = np.random.normal(size = (SIZE,))

A_slow_list, B_slow_list = list(A_quick_arr), list(B_quick_arr)

In [ ]:
%%time
ans = sum([A_slow_list[i] * B_slow_list[i] for i in range(SIZE)])

CPU times: user 3.37 s, sys: 118 ms, total: 3.49 s
Wall time: 3.5 s


In [ ]:
%%time
ans = np.sum(A_quick_arr * B_quick_arr)

CPU times: user 19.4 ms, sys: 951 µs, total: 20.4 ms
Wall time: 23 ms


In [ ]:
%%time
ans = A_quick_arr.dot(B_quick_arr)

CPU times: user 14.5 ms, sys: 0 ns, total: 14.5 ms
Wall time: 7.54 ms


## Pandas

<center> <img src = "https://www.influxdata.com/wp-content/uploads/pandas-influxdb.jpg" width = 50%> </center>

**Pandas** - библиотека для работы с табличными данными (обработка данных, аналитика и т.д.). В какой-то степени, свой язык запросов к данным.




In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/UCI_Credit_Card.csv')

Теперь данные хранятся в переменной ```df```, которая имеет тип [DataFrame](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html):

In [ ]:
type(df)

pandas.core.frame.DataFrame

DataFrame можно частично отобразить в jupyter-ноутбуке с помощью методов ```sample``` (случайная подвыборка), ```head``` (верхняя часть) и ```tail``` (нижняя часть):

In [ ]:
df.head()

ID  LIMIT_BAL  SEX  EDUCATION  ...  PAY_AMT4  PAY_AMT5  PAY_AMT6  target
0   1    20000.0    2          2  ...       0.0       0.0       0.0       1
1   2   120000.0    2          2  ...    1000.0       0.0    2000.0       1
2   3    90000.0    2          2  ...    1000.0    1000.0    5000.0       0
3   4    50000.0    2          2  ...    1100.0    1069.0    1000.0       0
4   5    50000.0    1          2  ...    9000.0     689.0     679.0       0

[5 rows x 25 columns]

In [ ]:
df.tail(3)

ID  LIMIT_BAL  SEX  EDUCATION  ...  PAY_AMT4  PAY_AMT5  PAY_AMT6  target
29997  29998    30000.0    1          2  ...    4200.0    2000.0    3100.0       1
29998  29999    80000.0    1          3  ...    1926.0   52964.0    1804.0       1
29999  30000    50000.0    1          2  ...    1000.0    1000.0    1000.0       1

[3 rows x 25 columns]

In [ ]:
df.sample(5)

ID  LIMIT_BAL  SEX  EDUCATION  ...  PAY_AMT4  PAY_AMT5  PAY_AMT6  target
7186    7187   240000.0    2          1  ...    3619.0   13227.0    7764.0       0
17606  17607    60000.0    2          1  ...    4749.0    5000.0   10000.0       0
2833    2834    50000.0    2          3  ...    1029.0    1054.0     977.0       0
16850  16851   230000.0    1          2  ...       0.0    1056.0     326.0       0
15477  15478   200000.0    1          2  ...    2000.0    2000.0    2000.0       0

[5 rows x 25 columns]

Можно отобразить и весь датасет, но это обычно слишком громоздко:

In [ ]:
df

ID  LIMIT_BAL  SEX  EDUCATION  ...  PAY_AMT4  PAY_AMT5  PAY_AMT6  target
0          1    20000.0    2          2  ...       0.0       0.0       0.0       1
1          2   120000.0    2          2  ...    1000.0       0.0    2000.0       1
2          3    90000.0    2          2  ...    1000.0    1000.0    5000.0       0
3          4    50000.0    2          2  ...    1100.0    1069.0    1000.0       0
4          5    50000.0    1          2  ...    9000.0     689.0     679.0       0
...      ...        ...  ...        ...  ...       ...       ...       ...     ...
29995  29996   220000.0    1          3  ...    3047.0    5000.0    1000.0       0
29996  29997   150000.0    1          3  ...     129.0       0.0       0.0       0
29997  29998    30000.0    1          2  ...    4200.0    2000.0    3100.0       1
29998  29999    80000.0    1          3  ...    1926.0   52964.0    1804.0       1
29999  30000    50000.0    1          2  ...    1000.0    1000.0    1000.0       1

[30000 rows x 25 columns]

DataFrame по сути является двумерной табличкой с набором полезных методов. Давайте рассмотрим основные из них.

В DataFrame есть несколько методов для обращения к строкам, столбцам и отдельным элементам таблицы: методы ```loc```, ```iloc``` и через квадратные скобки. Давайте поймем, в чем между ними разница, на примерах.

В метод ```loc``` можно передать значение индекса (число, которое стоит в колонке index) строки, чтобы получить эту строку:

In [ ]:
df.head(3)

ID  LIMIT_BAL  SEX  EDUCATION  ...  PAY_AMT4  PAY_AMT5  PAY_AMT6  target
0   1    20000.0    2          2  ...       0.0       0.0       0.0       1
1   2   120000.0    2          2  ...    1000.0       0.0    2000.0       1
2   3    90000.0    2          2  ...    1000.0    1000.0    5000.0       0

[3 rows x 25 columns]

In [ ]:
df.loc[2]

ID               3.0
LIMIT_BAL    90000.0
SEX              2.0
EDUCATION        2.0
MARRIAGE         2.0
AGE             34.0
PAY_0            0.0
PAY_2            0.0
PAY_3            0.0
PAY_4            0.0
PAY_5            0.0
PAY_6            0.0
BILL_AMT1    29239.0
BILL_AMT2    14027.0
BILL_AMT3    13559.0
BILL_AMT4    14331.0
BILL_AMT5    14948.0
BILL_AMT6    15549.0
PAY_AMT1      1518.0
PAY_AMT2      1500.0
PAY_AMT3      1000.0
PAY_AMT4      1000.0
PAY_AMT5      1000.0
PAY_AMT6      5000.0
target           0.0
Name: 2, dtype: float64

Получили отдельную строчку в виде объекта класса [Series](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html):

In [ ]:
type(df.loc[2])

pandas.core.series.Series

А с помощью срезов можно выбрать часть таблицы:

In [ ]:
df.loc[2:4]

ID  LIMIT_BAL  SEX  EDUCATION  ...  PAY_AMT4  PAY_AMT5  PAY_AMT6  target
2   3    90000.0    2          2  ...    1000.0    1000.0    5000.0       0
3   4    50000.0    2          2  ...    1100.0    1069.0    1000.0       0
4   5    50000.0    1          2  ...    9000.0     689.0     679.0       0

[3 rows x 25 columns]

Срез в ```loc``` производится по index и включает в себя последний элемент.

Метод ```iloc``` действует похожим образом, но он индексирует элементы не по index, а по порядку в таблице (который может отличаться от index). Например:

In [ ]:
subset = df.sample(5)
subset

ID  LIMIT_BAL  SEX  EDUCATION  ...  PAY_AMT4  PAY_AMT5  PAY_AMT6  target
24196  24197    80000.0    1          2  ...   35000.0    3000.0    2000.0       0
19141  19142   250000.0    2          3  ...   23122.0    4000.0   28650.0       0
5234    5235   150000.0    2          1  ...    2969.0    8642.0       0.0       0
527      528   620000.0    2          2  ...    6000.0    6500.0    6000.0       1
29536  29537   210000.0    1          1  ...       0.0       0.0       0.0       0

[5 rows x 25 columns]

In [ ]:
subset.iloc[2]

ID             5235.0
LIMIT_BAL    150000.0
SEX               2.0
EDUCATION         1.0
MARRIAGE          2.0
AGE              27.0
PAY_0            -1.0
PAY_2            -1.0
PAY_3            -1.0
PAY_4            -1.0
PAY_5            -1.0
PAY_6            -1.0
BILL_AMT1      7310.0
BILL_AMT2      4756.0
BILL_AMT3      1919.0
BILL_AMT4      8144.0
BILL_AMT5      2969.0
BILL_AMT6      8642.0
PAY_AMT1       4756.0
PAY_AMT2       1919.0
PAY_AMT3       8144.0
PAY_AMT4       2969.0
PAY_AMT5       8642.0
PAY_AMT6          0.0
target            0.0
Name: 5234, dtype: float64

In [ ]:
subset.loc[2]

KeyError: ignored

С помощью ```iloc``` тоже можно делать срезы, но в них последний элемент не включается (как и в обычных срезах в Python):

In [ ]:
df.iloc[2:4]

ID  LIMIT_BAL  SEX  EDUCATION  ...  PAY_AMT4  PAY_AMT5  PAY_AMT6  target
2   3    90000.0    2          2  ...    1000.0    1000.0    5000.0       0
3   4    50000.0    2          2  ...    1100.0    1069.0    1000.0       0

[2 rows x 25 columns]

Срезы можно брать не только по строкам, но и по столбцам. Обратите внимание на различия индексации столбцов в ```loc``` и ```iloc```:

In [ ]:
df.iloc[2:4,0:3]

ID  LIMIT_BAL  SEX
2   3    90000.0    2
3   4    50000.0    2

In [ ]:
df.loc[2:4, 'ID':'SEX']

ID  LIMIT_BAL  SEX
2   3    90000.0    2
3   4    50000.0    2
4   5    50000.0    1

Через квадратные скобки можно обращаться к одной или нескольким колонкам:

In [ ]:
df['AGE'].head()

0    24
1    26
2    34
3    37
4    57
Name: AGE, dtype: int64

In [ ]:
df[['AGE', 'EDUCATION', 'LIMIT_BAL']].head()

AGE  EDUCATION  LIMIT_BAL
0   24          2    20000.0
1   26          2   120000.0
2   34          2    90000.0
3   37          2    50000.0
4   57          2    50000.0

In [ ]:
df.loc[2:4, ['AGE', 'EDUCATION', 'LIMIT_BAL']]	

AGE  EDUCATION  LIMIT_BAL
2   34          2    90000.0
3   37          2    50000.0
4   57          2    50000.0

Также можно отбирать/фильтровать данные по значениям столбцов через прописывание условия внутри квадратных скобок от исходных данных



In [ ]:
df['LIMIT_BAL'] >= 50000

0        False
1         True
2         True
3         True
4         True
         ...  
29995     True
29996     True
29997    False
29998     True
29999     True
Name: LIMIT_BAL, Length: 30000, dtype: bool

In [ ]:
df[df['LIMIT_BAL'] >= 50000]


ID  LIMIT_BAL  SEX  EDUCATION  ...  PAY_AMT5  PAY_AMT6  target  5_LIMIT
1          2   120000.0    2          2  ...       0.0    2000.0       1        5
2          3    90000.0    2          2  ...    1000.0    5000.0       0        5
3          4    50000.0    2          2  ...    1069.0    1000.0       0        5
4          5    50000.0    1          2  ...     689.0     679.0       0        5
5          6    50000.0    1          1  ...    1000.0     800.0       0        5
...      ...        ...  ...        ...  ...       ...       ...     ...      ...
29994  29995    80000.0    1          2  ...       0.0    4000.0       1        5
29995  29996   220000.0    1          3  ...    5000.0    1000.0       0        5
29996  29997   150000.0    1          3  ...       0.0       0.0       0        5
29998  29999    80000.0    1          3  ...   52964.0    1804.0       1        5
29999  30000    50000.0    1          2  ...    1000.0    1000.0       1        5

[25689 rows x 26 columns]

Множественную фильрацию можно делать следующим образом 

* ```&``` для условия И (**and**)
* ```|``` для условия ИЛИ (**or**)

In [ ]:
df[(df['LIMIT_BAL'] >= 50000) & (df['EDUCATION'] == 2)]

ID  LIMIT_BAL  SEX  EDUCATION  ...  PAY_AMT5  PAY_AMT6  target  5_LIMIT
1          2   120000.0    2          2  ...       0.0    2000.0       1        5
2          3    90000.0    2          2  ...    1000.0    5000.0       0        5
3          4    50000.0    2          2  ...    1069.0    1000.0       0        5
4          5    50000.0    1          2  ...     689.0     679.0       0        5
7          8   100000.0    2          2  ...    1687.0    1542.0       0        5
...      ...        ...  ...        ...  ...       ...       ...     ...      ...
29982  29983    90000.0    1          2  ...    2500.0       0.0       1        5
29990  29991   140000.0    1          2  ...    2000.0    2000.0       0        5
29991  29992   210000.0    1          2  ...       0.0       0.0       1        5
29994  29995    80000.0    1          2  ...       0.0    4000.0       1        5
29999  30000    50000.0    1          2  ...    1000.0    1000.0       1        5

[11608 rows x 26 columns]

In [ ]:
df[df['EDUCATION'].isin([2, 3])]

ID  LIMIT_BAL  SEX  EDUCATION  ...  PAY_AMT5  PAY_AMT6  target  5_LIMIT
0          1    20000.0    2          2  ...       0.0       0.0       1        5
1          2   120000.0    2          2  ...       0.0    2000.0       1        5
2          3    90000.0    2          2  ...    1000.0    5000.0       0        5
3          4    50000.0    2          2  ...    1069.0    1000.0       0        5
4          5    50000.0    1          2  ...     689.0     679.0       0        5
...      ...        ...  ...        ...  ...       ...       ...     ...      ...
29995  29996   220000.0    1          3  ...    5000.0    1000.0       0        5
29996  29997   150000.0    1          3  ...       0.0       0.0       0        5
29997  29998    30000.0    1          2  ...    2000.0    3100.0       1        5
29998  29999    80000.0    1          3  ...   52964.0    1804.0       1        5
29999  30000    50000.0    1          2  ...    1000.0    1000.0       1        5

[18947 rows x 26 columns]

In [ ]:
df[(df['EDUCATION'].isin([2, 3])) | (df['LIMIT_BAL'] >= 100000)]

ID  LIMIT_BAL  SEX  EDUCATION  ...  PAY_AMT5  PAY_AMT6  target  5_LIMIT
0          1    20000.0    2          2  ...       0.0       0.0       1        5
1          2   120000.0    2          2  ...       0.0    2000.0       1        5
2          3    90000.0    2          2  ...    1000.0    5000.0       0        5
3          4    50000.0    2          2  ...    1069.0    1000.0       0        5
4          5    50000.0    1          2  ...     689.0     679.0       0        5
...      ...        ...  ...        ...  ...       ...       ...     ...      ...
29995  29996   220000.0    1          3  ...    5000.0    1000.0       0        5
29996  29997   150000.0    1          3  ...       0.0       0.0       0        5
29997  29998    30000.0    1          2  ...    2000.0    3100.0       1        5
29998  29999    80000.0    1          3  ...   52964.0    1804.0       1        5
29999  30000    50000.0    1          2  ...    1000.0    1000.0       1        5

[27476 rows x 26 columns]

Помимо отрицания `!=` можно использовать тильду к логическому выражению `~`

In [ ]:
df[df['EDUCATION'] != 2].head()

ID  LIMIT_BAL  SEX  EDUCATION  ...  PAY_AMT5  PAY_AMT6  target  5_LIMIT
5    6    50000.0    1          1  ...    1000.0     800.0       0        5
6    7   500000.0    1          1  ...   13750.0   13770.0       0        5
8    9   140000.0    2          3  ...    1000.0    1000.0       0        5
9   10    20000.0    1          3  ...    1122.0       0.0       0        5
10  11   200000.0    2          3  ...    3738.0      66.0       0        5

[5 rows x 26 columns]

In [ ]:
df[~(df['EDUCATION'].isin([2, 3]))].sample(5)

ID  LIMIT_BAL  SEX  EDUCATION  ...  PAY_AMT5  PAY_AMT6  target  5_LIMIT
22574  22575   420000.0    2          1  ...    7705.0    7246.0       0        5
8317    8318    60000.0    1          1  ...    1200.0    1233.0       0        5
25354  25355    50000.0    2          1  ...    2880.0     390.0       0        5
6184    6185   150000.0    1          1  ...    5219.0   50005.0       0        5
17193  17194   110000.0    2          1  ...   31775.0    1152.0       1        5

[5 rows x 26 columns]

С DataFrame'ами и Series'ами одинаковой структуры можно производить математические операции:

In [ ]:
crappy_var = df.LIMIT_BAL ** 2 * df.PAY_0 + df.BILL_AMT1 - df.PAY_AMT1
crappy_var.head()

0    8.000039e+08
1   -1.440000e+10
2    2.772100e+04
3    4.499000e+04
4   -2.499993e+09
dtype: float64

Можно создать новую переменную в таблице

In [ ]:
df['SUM_OF_BILLS'] = df['BILL_AMT1'] + df['BILL_AMT2'] + df['BILL_AMT3'] + df['BILL_AMT4'] + df['BILL_AMT5'] + df['BILL_AMT6']

df['BIILS_TO_LIMIT'] = df['SUM_OF_BILLS'] / df['LIMIT_BAL']

In [ ]:
cols = df.columns
cols_selected = cols[cols.str.contains('BILL_')]

df['SUM_OF_BILLS'] = df[cols_selected].sum(axis = 1)

Можно создать переменную согласно какому-то условию с помощью `np.where`

In [ ]:
df['MARITAL_STATUS'] = np.where(df['MARRIAGE'] == 2, 'MARRIED', 
                                np.where(df['MARRIAGE'] == 1, 'NOT MARRIED', 'OTHER'))

In [ ]:
df.head()

ID  LIMIT_BAL  SEX  ...  SUM_OF_BILLS  BIILS_TO_LIMIT  MARITAL_STATUS
0   1    20000.0    2  ...        7704.0        0.385200     NOT MARRIED
1   2   120000.0    2  ...       17077.0        0.142308         MARRIED
2   3    90000.0    2  ...      101653.0        1.129478         MARRIED
3   4    50000.0    2  ...      231334.0        4.626680     NOT MARRIED
4   5    50000.0    1  ...      109339.0        2.186780     NOT MARRIED

[5 rows x 29 columns]

Также можно отфильтровать наблюдения, у которых "строковая" переменная содержит какую-то строку.

In [ ]:
df[df.MARITAL_STATUS.str.contains('OTH')]

ID  LIMIT_BAL  SEX  ...  SUM_OF_BILLS  BIILS_TO_LIMIT  MARITAL_STATUS
15        16    50000.0    2  ...      196416.0        3.928320           OTHER
51        52   100000.0    2  ...      265185.0        2.651850           OTHER
80        81   470000.0    2  ...      614823.0        1.308134           OTHER
218      219   110000.0    2  ...      453847.0        4.125882           OTHER
239      240   140000.0    2  ...      115854.0        0.827529           OTHER
...      ...        ...  ...  ...           ...             ...             ...
29282  29283    80000.0    2  ...       11453.0        0.143162           OTHER
29509  29510   200000.0    1  ...      703741.0        3.518705           OTHER
29612  29613    20000.0    1  ...        2340.0        0.117000           OTHER
29745  29746    20000.0    1  ...       72302.0        3.615100           OTHER
29931  29932    60000.0    1  ...      180878.0        3.014633           OTHER

[377 rows x 29 columns]

Можно удалять переменные

In [ ]:
df = df.drop(columns = ['MARITAL_STATUS'])
# df.drop(columns = ['MARITAL_STATUS'], inplace = True)
df.head()

# второй вариант, inplace = True позволяет избежать присваивания
# df.drop('new', axis = 1, inplace = True)

ID  LIMIT_BAL  SEX  EDUCATION  ...  target  5_LIMIT  SUM_OF_BILLS  BIILS_TO_LIMIT
0   1    20000.0    2          2  ...       1        5        7704.0        0.385200
1   2   120000.0    2          2  ...       1        5       17077.0        0.142308
2   3    90000.0    2          2  ...       0        5      101653.0        1.129478
3   4    50000.0    2          2  ...       0        5      231334.0        4.626680
4   5    50000.0    1          2  ...       0        5      109339.0        2.186780

[5 rows x 28 columns]

К данным можно применять преобразования или какие-то операции. 

Метод ```.apply(..)``` примененный к данным (но тогда требуется уточнение к каким столбцам) или к столбцу данных, применяет поэлементно функцию к тому, к чему вызывался. 

In [ ]:
# .astype(int) переводит в целочисленный формат данных, т.к. результат .apply(..) возвращает булево значение
df['LIMIT_BAL_MORE_50K'] = df.apply(lambda x: x['LIMIT_BAL'] > 50000, axis = 1).astype('int')
df['LIMIT_BAL_LESSEQ_50K'] = df.apply(lambda x: x['LIMIT_BAL'] <= 50000, axis = 1).astype('int')

In [ ]:
df['LIMIT_BAL_MORE_50K'] = df['LIMIT_BAL'].apply(lambda x: x > 50000).astype(int)

Для каждого элемента ниже применяется функция (прописанная через лямбда-функцию), которая для каждого элемента столбца **tdate** переводит его в строку, срезает первые 4 элемента и переводит в целочисленный тип данных.

In [ ]:
df.head(3)

ID  LIMIT_BAL  SEX  ...  BIILS_TO_LIMIT  LIMIT_BAL_MORE_50K  LIMIT_BAL_LESSEQ_50K
0   1    20000.0    2  ...        0.385200                   0                     1
1   2   120000.0    2  ...        0.142308                   1                     0
2   3    90000.0    2  ...        1.129478                   1                     0

[3 rows x 30 columns]

К столбцам (как и к таблице) можно применять различные полезные методы. 
Посчитаем количество представленных ступеней образования:

In [ ]:
df.EDUCATION.value_counts()

2    14030
1    10585
3     4917
5      280
4      123
6       51
0       14
Name: EDUCATION, dtype: int64

In [ ]:
df.EDUCATION.value_counts(normalize = True)

2    0.467667
1    0.352833
3    0.163900
5    0.009333
4    0.004100
6    0.001700
0    0.000467
Name: EDUCATION, dtype: float64

In [ ]:
educ_uniq_counts = df.EDUCATION.value_counts(normalize = True)

educ_uniq_counts.values

array([4.67666667e-01, 3.52833333e-01, 1.63900000e-01, 9.33333333e-03,
       4.10000000e-03, 1.70000000e-03, 4.66666667e-04])

In [ ]:
educ_uniq_counts.index

Int64Index([2, 1, 3, 5, 4, 6, 0], dtype='int64')

Посмотреть еще можно на статистики по переменной (```.mean()```, ```.std()```, ```.median()```, ```.min()```, ```.max()```), так и вывести все уникальные значения переменной - ```.unique()```, или вывести количество уникальных значений - ```.nunique()```

In [ ]:
df.EDUCATION.nunique()

7

In [ ]:
df.EDUCATION.unique()

array([2, 1, 3, 5, 4, 6, 0])

In [ ]:
df.LIMIT_BAL.median(), df.LIMIT_BAL.mean()

(140000.0, 167484.32266666667)

In [ ]:
df.LIMIT_BAL.std(), df.LIMIT_BAL.quantile(0.99)

(129747.66156719506, 500000.0)

Посмотрим на основные статистики по числовым признакам:

In [ ]:
df.describe()

ID       LIMIT_BAL  ...  LIMIT_BAL_MORE_50K  LIMIT_BAL_LESSEQ_50K
count  30000.000000    30000.000000  ...        30000.000000          30000.000000
mean   15000.500000   167484.322667  ...            0.744133              0.255867
std     8660.398374   129747.661567  ...            0.436355              0.436355
min        1.000000    10000.000000  ...            0.000000              0.000000
25%     7500.750000    50000.000000  ...            0.000000              0.000000
50%    15000.500000   140000.000000  ...            1.000000              0.000000
75%    22500.250000   240000.000000  ...            1.000000              1.000000
max    30000.000000  1000000.000000  ...            1.000000              1.000000

[8 rows x 30 columns]

Также к данным можно применять аггрегации по группам. Например, мы хотим посмотреть на средний лимит **LIMIT_BAL** для каждого значения в **EDUCATION**

Аггрегация - частая операция. Например, мы можем иметь целые истории наблюдений по пользователям. Нам может понадобиться посмотреть на средние значения для каждого пользователя.

In [ ]:
df.groupby('EDUCATION')['LIMIT_BAL'].mean()

EDUCATION
0    217142.857143
1    212956.069910
2    147062.437634
3    126550.270490
4    220894.308943
5    168164.285714
6    148235.294118
Name: LIMIT_BAL, dtype: float64

In [ ]:
# а можно аггрегировать по нескольким переменным
df.groupby(['EDUCATION', 'SEX'])['LIMIT_BAL'].mean().reset_index(name = 'MEAN_LIMIT_BAL')

EDUCATION  SEX  MEAN_LIMIT_BAL
0           0    1   212500.000000
1           0    2   223333.333333
2           1    1   219251.263206
3           1    2   208557.213930
4           2    1   133902.121325
5           2    2   155232.902033
6           3    1   120943.557789
7           3    2   130362.145542
8           4    1   197142.857143
9           4    2   233209.876543
10          5    1   159221.052632
11          5    2   172756.756757
12          6    1   157200.000000
13          6    2   139615.384615

In [ ]:
# и для нескольких переменных получать аггрегаты
df.groupby(['EDUCATION', 'SEX'])[['LIMIT_BAL', 'AGE']].mean().reset_index()

EDUCATION  SEX      LIMIT_BAL        AGE
0           0    1  212500.000000  37.625000
1           0    2  223333.333333  40.500000
2           1    1  219251.263206  35.954754
3           1    2  208557.213930  33.027925
4           2    1  133902.121325  35.550428
5           2    2  155232.902033  34.207833
6           3    1  120943.557789  40.336683
7           3    2  130362.145542  40.275026
8           4    1  197142.857143  33.976190
9           4    2  233209.876543  33.790123
10          5    1  159221.052632  36.147368
11          5    2  172756.756757  35.318919
12          6    1  157200.000000  44.640000
13          6    2  139615.384615  43.192308

In [ ]:
# а можно применять и несколько функций сразу
df.groupby('EDUCATION')['LIMIT_BAL'].agg({'mean', 'min', 'max', np.median}).reset_index()

EDUCATION           mean      min        max    median
0          0  217142.857143  50000.0   360000.0  215000.0
1          1  212956.069910  10000.0  1000000.0  200000.0
2          2  147062.437634  10000.0   800000.0  110000.0
3          3  126550.270490  10000.0   760000.0   80000.0
4          4  220894.308943  20000.0   710000.0  200000.0
5          5  168164.285714  10000.0   550000.0  150000.0
6          6  148235.294118  10000.0   540000.0  100000.0

In [ ]:
def return_nuniq(x):
  return x.nunique()

In [ ]:
df.groupby('EDUCATION')['LIMIT_BAL'].apply(return_nuniq)

EDUCATION
0    13
1    76
2    75
3    66
4    40
5    45
6    24
Name: LIMIT_BAL, dtype: int64

Может потребоваться наличие средних лимитов по уровню образования в таблице

Настоятельно рекомендуется посмотреть типы джоинов (left, inner, right, outer)


<center> <img src = "https://i2.wp.com/www.datascienceexamples.com/wp-content/uploads/2019/12/join_types.png?resize=840%2C560&ssl=1" width = 75%> </center>



Присоединять можно и не по одной переменной, а по нескольким - тогда ```on = ['VAR_1', 'VAR_2']```

In [ ]:
avg_lim_educ = df.groupby('EDUCATION')['LIMIT_BAL'].mean().reset_index(name = 'AVG_LIMIT_BY_EDUCATION')

df = df.merge(avg_lim_educ, how = 'left', on = 'EDUCATION')

In [ ]:
df[['EDUCATION', 'AVG_LIMIT_BY_EDUCATION']].drop_duplicates()

EDUCATION  AVG_LIMIT_BY_EDUCATION
0             2           147062.437634
5             1           212956.069910
8             3           126550.270490
47            5           168164.285714
358           4           220894.308943
502           6           148235.294118
3769          0           217142.857143

In [ ]:
avg_lim_educ.sort_values(by = ['EDUCATION'], ascending = False)

EDUCATION  AVG_LIMIT_BY_EDUCATION
6          6           148235.294118
5          5           168164.285714
4          4           220894.308943
3          3           126550.270490
2          2           147062.437634
1          1           212956.069910
0          0           217142.857143

Также можно встретить столбцы с пропущенными переменными. Их можно заменить на какие-либо значеня - на среднее/медиану (или какую-либо другую статистику) по столбцу, на ноль, на строчку, на какое-то другое абстрактное число.

In [ ]:
# создадим перед этим незаполненную переменную, заполним ее по какому-нибудь надуманному правилу
df['var_with_na'] = np.where(df['AGE'].isin([37, 38, 39, 40]), np.nan, df['LIMIT_BAL'])

In [ ]:
df.head()

ID  LIMIT_BAL  ...  AVG_LIMIT_BY_EDUCATION  var_with_na
0   1    20000.0  ...           147062.437634      20000.0
1   2   120000.0  ...           147062.437634     120000.0
2   3    90000.0  ...           147062.437634      90000.0
3   4    50000.0  ...           147062.437634          NaN
4   5    50000.0  ...           147062.437634      50000.0

[5 rows x 32 columns]

In [ ]:
df[df['var_with_na'].isnull()].head()

ID  LIMIT_BAL  ...  AVG_LIMIT_BY_EDUCATION  var_with_na
3    4    50000.0  ...           147062.437634          NaN
5    6    50000.0  ...           212956.069910          NaN
20  21   130000.0  ...           126550.270490          NaN
21  22   120000.0  ...           147062.437634          NaN
23  24   450000.0  ...           212956.069910          NaN

[5 rows x 32 columns]

In [ ]:
np.isnan(df['var_with_na']).sum()

3809

In [ ]:
df[df['AGE'].isin([37, 38, 39, 40])]['var_with_na'].head()

3    NaN
5    NaN
20   NaN
21   NaN
23   NaN
Name: var_with_na, dtype: float64

In [ ]:
a = np.array([1, 2, np.nan])
np.nanmean(a)

1.5

In [ ]:
df['var_with_na_fill'] = df['var_with_na'].fillna(df['var_with_na'].mean())
df.head()

ID  LIMIT_BAL  SEX  ...  AVG_LIMIT_BY_EDUCATION  var_with_na  var_with_na_fill
0   1    20000.0    2  ...           147062.437634      20000.0      20000.000000
1   2   120000.0    2  ...           147062.437634     120000.0     120000.000000
2   3    90000.0    2  ...           147062.437634      90000.0      90000.000000
3   4    50000.0    2  ...           147062.437634          NaN     163157.560994
4   5    50000.0    1  ...           147062.437634      50000.0      50000.000000

[5 rows x 33 columns]

In [ ]:
df['var_with_na_fill_gr'] = df['var_with_na'].fillna(df.groupby('EDUCATION')['var_with_na'].mean())
df.head()

ID  LIMIT_BAL  SEX  ...  var_with_na  var_with_na_fill  var_with_na_fill_gr
0   1    20000.0    2  ...      20000.0      20000.000000         20000.000000
1   2   120000.0    2  ...     120000.0     120000.000000        120000.000000
2   3    90000.0    2  ...      90000.0      90000.000000         90000.000000
3   4    50000.0    2  ...          NaN     163157.560994        122779.814643
4   5    50000.0    1  ...      50000.0      50000.000000         50000.000000

[5 rows x 34 columns]

In [ ]:
df.groupby('EDUCATION')['var_with_na'].mean()

EDUCATION
0    236666.666667
1    207381.696669
2    143337.653815
3    122779.814643
4    216696.428571
5    161816.666667
6    147659.574468
Name: var_with_na, dtype: float64

Возвращаясь к группировкам, иногда (для отсортированных данных) требуется для пользователя взять первое наблюдение в данных, или первое наблюдение в месяце (или последнее). Можно использовать при группировке методы ```.first()``` и ```last()```

In [ ]:
df.groupby('AGE').first().head(5)

ID  LIMIT_BAL  SEX  ...  var_with_na  var_with_na_fill  var_with_na_fill_gr
AGE                       ...                                                    
21   530    20000.0    2  ...      20000.0           20000.0              20000.0
22    38    60000.0    2  ...      60000.0           60000.0              60000.0
23     8   100000.0    2  ...     100000.0          100000.0             100000.0
24     1    20000.0    2  ...      20000.0           20000.0              20000.0
25    39    50000.0    1  ...      50000.0           50000.0              50000.0

[5 rows x 33 columns]

## Операции над датами и временем

Часто является необходимостью обрабатывать переменные дат и времени. Как правило, при прочтении они представлены в строковом формате. Однако для подсчета разинцы между датами, а также для более "приятного" их отображения на осях, требуется переводить в формат дат.

Даты могут быть даны в разных форматах и с разными разделителями.

Более подробно здесь [про даты: клац](https://docs.python.org/3/library/datetime.html)

In [ ]:
from datetime import datetime as dt
import datetime
from dateutil.relativedelta import relativedelta

Создадим дату в строковом формате и переведем ее в формат времени. Формат времени также выдает помимо даты часы. Методом ```.date()``` можно оставить только дату.

In [ ]:
date = '2020-07-31'

date = dt.strptime(date, '%Y-%m-%d')
print(date)
print(type(date))
print(date.date())
print(date.day)
print(date.month)

2020-07-31 00:00:00
<class 'datetime.datetime'>
2020-07-31
31
7


In [ ]:
date.hour

0

In [ ]:
date = '2020:Jan:25'

date = dt.strptime(date, '%Y:%b:%d')
print(date)
print(type(date))
print(date.date())
print(date.day)
print(date.month)

2020-01-25 00:00:00
<class 'datetime.datetime'>
2020-01-25
25
1


In [ ]:
var_datetime = '2020-01-13 23:58:00'

var_datetime = dt.strptime(var_datetime, '%Y-%m-%d %H:%M:%S')
var_datetime

datetime.datetime(2020, 1, 13, 23, 58)

In [ ]:
var_datetime.hour

23

In [ ]:
# df['DateColumn'].apply(lambda x: dt.strptime(x, 'format'))

Можно также добавить месяц (или день) через ```relativedelta()``` к нашей дате. Метод добавляет не 30 или 31 день, а возвращает дату через месяц.

In [ ]:
date_2 = date.date() + relativedelta(months = 1)
print(date_2)

2020-02-25


In [ ]:
[date.date() + relativedelta(months = i) for i in range(1, 13)]

[datetime.date(2020, 2, 25),
 datetime.date(2020, 3, 25),
 datetime.date(2020, 4, 25),
 datetime.date(2020, 5, 25),
 datetime.date(2020, 6, 25),
 datetime.date(2020, 7, 25),
 datetime.date(2020, 8, 25),
 datetime.date(2020, 9, 25),
 datetime.date(2020, 10, 25),
 datetime.date(2020, 11, 25),
 datetime.date(2020, 12, 25),
 datetime.date(2021, 1, 25)]

Для подсчета разницы, надо не забыть применить ```.date()``` к **date** (т.к. пока что там есть еще и время)

In [ ]:
tmp = date_2 - date.date()

In [ ]:
tmp.days

31

**План на следующее занятие**

* Непокрытое - итераторы, генераторы, векторизация в NumPy, чтение файлов json/txt
* Визуализация (основное)
* Оптимизация (если время позволит)
